import PropTypes from "prop-types";
import * as ProjectConstants from 'constants/projectConstants.js';
import { matchesUUID } from "components/tree/propTypes";

const INPUT_FILE_PROPTYPES = {
  resource_id: matchesUUID,
  file_collection_id: matchesUUID,
  file_collection_paths: PropTypes.arrayOf(PropTypes.string),
  path: PropTypes.string,
}

export const ModelControlPropTypes = PropTypes.shape({
  id: matchesUUID,
  attributes: PropTypes.object,
  created_by: PropTypes.string,
  date_created: PropTypes.instanceOf(Date),
  description: PropTypes.string,
  display_type_plural: PropTypes.string,
  display_type_singular: PropTypes.string,
  locked: PropTypes.bool,
  name: PropTypes.string,
  organizations: PropTypes.array,
  public: PropTypes.bool,
  slug: PropTypes.string,
  status: PropTypes.string,
  type: PropTypes.string,
  input_file: PropTypes.shape({
    file_name: PropTypes.string,
    run_parameters: PropTypes.shape({
      time_variables: PropTypes.shape({
        STARTDATE: PropTypes.instanceOf(Date),
        RUNTIME: PropTypes.number,
        TIMESTEP: PropTypes.number,
        GWSTEP: PropTypes.number,
        METSTEP: PropTypes.number,
        ETISTEP: PropTypes.number,
        RAININTRVL: PropTypes.number,
        OPINTRVL: PropTypes.number,
        SPOPINTRVL: PropTypes.number,
        INTSTORMMAX: PropTypes.number,
        RAINSEARCH: PropTypes.number,
      }),
      routing_variables: PropTypes.shape({
        BASEFLOW: PropTypes.number,
        VELOCITYCOEF: PropTypes.number,
        VELOCITYRATIO: PropTypes.number,
        KINEMVELCOEF: PropTypes.number,
        FLOWEXP: PropTypes.number,
        CHANNELROUGHNESS: PropTypes.number,
        CHANNELWIDTH: PropTypes.number,
        CHANNELWIDTHCOEFF: PropTypes.number,
        CHANNELWIDTHEXPNT: PropTypes.number,
        CHANNELWIDTHFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
      }),
      meteorological_variables: PropTypes.shape({
        TLINKE: PropTypes.number,
        MINSNTEMP: PropTypes.number,
        TEMPLAPSE: PropTypes.number,
        PRECLAPSE: PropTypes.number,
        SNLIQFRAC: PropTypes.number,
      }),
    }),
    run_options: PropTypes.shape({
      OPTMESHINPUT: PropTypes.oneOf(Object.values(ProjectConstants.OPTMESHINPUT)),
      RAINSOURCE: PropTypes.oneOf(Object.values(ProjectConstants.RAINSOURCE)),
      OPTEVAPOTRANS: PropTypes.oneOf(Object.values(ProjectConstants.OPTEVAPOTRANS)),
      OPTSNOW: PropTypes.oneOf(Object.values(ProjectConstants.OPTSNOW)),
      HILLALBOPT: PropTypes.oneOf(Object.values(ProjectConstants.HILLALBOPT)),
      OPTRADSHELT: PropTypes.oneOf(Object.values(ProjectConstants.OPTRADSHELT)),
      OPTINTERCEPT: PropTypes.oneOf(Object.values(ProjectConstants.OPTINTERCEPT)),
      OPTLANDUSE: PropTypes.oneOf(Object.values(ProjectConstants.OPTLANDUSE)),
      OPTLUINTERP: PropTypes.oneOf(Object.values(ProjectConstants.OPTLUINTERP)),
      GFLUXOPTION: PropTypes.oneOf(Object.values(ProjectConstants.GFLUXOPTION)),
      METDATAOPTION: PropTypes.oneOf(Object.values(ProjectConstants.METDATAOPTION)),
      CONVERTDATA: PropTypes.oneOf(Object.values(ProjectConstants.CONVERTDATA)),
      OPTBEDROCK: PropTypes.oneOf(Object.values(ProjectConstants.OPTBEDROCK)),
      OPTGROUNDWATER: PropTypes.oneOf(Object.values(ProjectConstants.OPTGROUNDWATER)),
      WIDTHINTERPOLATION: PropTypes.oneOf(Object.values(ProjectConstants.WIDTHINTERPOLATION)),
      OPTGWFILE: PropTypes.oneOf(Object.values(ProjectConstants.OPTGWFILE)),
      OPTRUNON: PropTypes.oneOf(Object.values(ProjectConstants.OPTRUNON)),
      OPTRESERVOIR: PropTypes.oneOf(Object.values(ProjectConstants.OPTRESERVOIR)),
      OPTSOILTYPE: PropTypes.oneOf(Object.values(ProjectConstants.OPTSOILTYPE)),
      OPTPERCOLATION: PropTypes.oneOf(Object.values(ProjectConstants.OPTPERCOLATION))
    }),
    files_and_pathnames: PropTypes.shape({
      mesh_generation: PropTypes.shape({
        INPUTDATAFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
        POINTFILENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
        INPUTTIME: PropTypes.any, // Type may vary based on ms.input_file?.files_and_pathnames?.mesh_generation?.INPUTTIME
        ARCINFOFILENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
      }),
      resampling_grids: PropTypes.shape({
        SOILTABLENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
        SOILMAPNAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
        LANDTABLENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
        LANDMAPNAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
        GWATERFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
        DEMFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
        RAINFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
        RAINEXTENSION: PropTypes.string,
        DEPTHTOBEDROCK: PropTypes.number,
        BEDROCKFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
        LUGRID: PropTypes.shape(INPUT_FILE_PROPTYPES),
        SCGRID: PropTypes.shape(INPUT_FILE_PROPTYPES),
      }),
      meteorological_data: PropTypes.shape({
        HYDROMETSTATIONS: PropTypes.shape(INPUT_FILE_PROPTYPES),
        HYDROMETGRID: PropTypes.shape(INPUT_FILE_PROPTYPES),
        HYDROMETCONVERT: PropTypes.shape(INPUT_FILE_PROPTYPES),
        HYDROMETBASENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
        GAUGESTATIONS: PropTypes.shape(INPUT_FILE_PROPTYPES),
        GAUGECONVERT: PropTypes.shape(INPUT_FILE_PROPTYPES),
        GAUGEBASENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
      }),
      output_data: PropTypes.shape({
        OUTFILENAME: PropTypes.shape({
          file_database_paths: PropTypes.array,
          path: PropTypes.string,
        }),
        OUTHYDROFILENAME: PropTypes.shape({
          file_database_paths: PropTypes.array,
          path: PropTypes.string,
        }),
        OUTHYDROEXTENSION: PropTypes.string, // This should be a certain file ext
        RIBSHYDOUTPUT: PropTypes.number,
        NODEOUTPUTLIST: PropTypes.shape(INPUT_FILE_PROPTYPES),
        HYDRONODELIST: PropTypes.shape(INPUT_FILE_PROPTYPES),
        OUTLETNODELIST: PropTypes.shape(INPUT_FILE_PROPTYPES),
        OPTSPATIAL: PropTypes.oneOf(Object.values(ProjectConstants.OPTSPATIAL)),
        OPTINTERHYDRO: PropTypes.oneOf(Object.values(ProjectConstants.OPTINTERHYDRO)),
        OPTHEADER: PropTypes.oneOf(Object.values(ProjectConstants.OPTHEADER)),
      }),
      resevoir_data: PropTypes.shape({
        RESPOLYGONID: PropTypes.shape(INPUT_FILE_PROPTYPES),
        RESDATA: PropTypes.shape(INPUT_FILE_PROPTYPES),
      }),
    }),
    modes: PropTypes.shape({
      rainfall_forecasting: PropTypes.shape({
        FORECASTMODE: PropTypes.oneOf(Object.values(ProjectConstants.FORECASTMODE)),
        FORECASTTIME: PropTypes.string,
        FORECASTLEADTIME: PropTypes.string,
        FORECASTLENGTH: PropTypes.string,
        FORECASTFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
        CLIMATOLOGY: PropTypes.string,
        RAINDISTRIBUTION: PropTypes.oneOf(Object.values(ProjectConstants.RAINDISTRIBUTION)),
      }),
      stochastic_climate_forcing: PropTypes.shape({
        STOCHASTICMODE: PropTypes.oneOf(Object.values(ProjectConstants.STOCHASTICMODE)),
        PMEAN: PropTypes.number,
        STDUR: PropTypes.number,
        ISTDUR: PropTypes.number,
        SEED: PropTypes.number,
        PERIOD: PropTypes.number,
        MAXPMEAN: PropTypes.number,
        MAXSTDURMN: PropTypes.number,
        MAXISTDURMN: PropTypes.number,
        WEATHERTABLENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
      }),
      restart: PropTypes.shape({
        RESTARTMODE: PropTypes.oneOf(Object.values(ProjectConstants.RESTARTMODE)),
        RESTARTINTRVL: PropTypes.number,
        RESTARTDIR: PropTypes.shape(INPUT_FILE_PROPTYPES),
        RESTARTFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
      }),
      parallel: PropTypes.shape({
        PARALLELMODE: PropTypes.oneOf(Object.values(ProjectConstants.PARALLELMODE)),
        GRAPHOPTION: PropTypes.oneOf(Object.values(ProjectConstants.GRAPHOPTION)),
        GRAPHFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
      }),
    }),
    visualization: PropTypes.shape({
      OPTVIZ: PropTypes.oneOf(Object.values(ProjectConstants.OPTVIZ)),
      OUTVIZFILENAME: PropTypes.shape(INPUT_FILE_PROPTYPES)
    }),
  }),
  linked_dataset: PropTypes.arrayOf(
    PropTypes.shape({
      id: matchesUUID,
      name: PropTypes.string,
    })
  ),
  realizations: PropTypes.arrayOf(
    PropTypes.shape({
      id: matchesUUID,
      attributes: PropTypes.object,
      created_by: PropTypes.string,
      date_created: PropTypes.instanceOf(Date),
      description: PropTypes.string,
      display_type_plural: PropTypes.string,
      display_type_singular: PropTypes.string,
      locked: PropTypes.bool,
      name: PropTypes.string,
      organizations: PropTypes.array,
      public: PropTypes.bool,
      slug: PropTypes.string,
      status: PropTypes.string,
      type: PropTypes.string,
      input_file: PropTypes.shape({
        file_name: PropTypes.string,
        run_parameters: PropTypes.shape({
          time_variables: PropTypes.shape({
            STARTDATE: PropTypes.instanceOf(Date),
            RUNTIME: PropTypes.number,
            TIMESTEP: PropTypes.number,
            GWSTEP: PropTypes.number,
            METSTEP: PropTypes.number,
            ETISTEP: PropTypes.number,
            RAININTRVL: PropTypes.number,
            OPINTRVL: PropTypes.number,
            SPOPINTRVL: PropTypes.number,
            INTSTORMMAX: PropTypes.number,
            RAINSEARCH: PropTypes.number,
          }),
          routing_variables: PropTypes.shape({
            BASEFLOW: PropTypes.number,
            VELOCITYCOEF: PropTypes.number,
            VELOCITYRATIO: PropTypes.number,
            KINEMVELCOEF: PropTypes.number,
            FLOWEXP: PropTypes.number,
            CHANNELROUGHNESS: PropTypes.number,
            CHANNELWIDTH: PropTypes.number,
            CHANNELWIDTHCOEFF: PropTypes.number,
            CHANNELWIDTHEXPNT: PropTypes.number,
            CHANNELWIDTHFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
          }),
          meteorological_variables: PropTypes.shape({
            TLINKE: PropTypes.number,
            MINSNTEMP: PropTypes.number,
            TEMPLAPSE: PropTypes.number,
            PRECLAPSE: PropTypes.number,
            SNLIQFRAC: PropTypes.number,
          }),
        }),
        run_options: PropTypes.shape({
          OPTMESHINPUT: PropTypes.oneOf(Object.values(ProjectConstants.OPTMESHINPUT)),
          RAINSOURCE: PropTypes.oneOf(Object.values(ProjectConstants.RAINSOURCE)),
          OPTEVAPOTRANS: PropTypes.oneOf(Object.values(ProjectConstants.OPTEVAPOTRANS)),
          OPTSNOW: PropTypes.oneOf(Object.values(ProjectConstants.OPTSNOW)),
          HILLALBOPT: PropTypes.oneOf(Object.values(ProjectConstants.HILLALBOPT)),
          OPTRADSHELT: PropTypes.oneOf(Object.values(ProjectConstants.OPTRADSHELT)),
          OPTINTERCEPT: PropTypes.oneOf(Object.values(ProjectConstants.OPTINTERCEPT)),
          OPTLANDUSE: PropTypes.oneOf(Object.values(ProjectConstants.OPTLANDUSE)),
          OPTLUINTERP: PropTypes.oneOf(Object.values(ProjectConstants.OPTLUINTERP)),
          GFLUXOPTION: PropTypes.oneOf(Object.values(ProjectConstants.GFLUXOPTION)),
          METDATAOPTION: PropTypes.oneOf(Object.values(ProjectConstants.METDATAOPTION)),
          CONVERTDATA: PropTypes.oneOf(Object.values(ProjectConstants.CONVERTDATA)),
          OPTBEDROCK: PropTypes.oneOf(Object.values(ProjectConstants.OPTBEDROCK)),
          OPTGROUNDWATER: PropTypes.oneOf(Object.values(ProjectConstants.OPTGROUNDWATER)),
          WIDTHINTERPOLATION: PropTypes.oneOf(Object.values(ProjectConstants.WIDTHINTERPOLATION)),
          OPTGWFILE: PropTypes.oneOf(Object.values(ProjectConstants.OPTGWFILE)),
          OPTRUNON: PropTypes.oneOf(Object.values(ProjectConstants.OPTRUNON)),
          OPTRESERVOIR: PropTypes.oneOf(Object.values(ProjectConstants.OPTRESERVOIR)),
          OPTSOILTYPE: PropTypes.oneOf(Object.values(ProjectConstants.OPTSOILTYPE)),
          OPTPERCOLATION: PropTypes.oneOf(Object.values(ProjectConstants.OPTPERCOLATION))
        }),
        files_and_pathnames: PropTypes.shape({
          mesh_generation: PropTypes.shape({
            INPUTDATAFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
            POINTFILENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
            INPUTTIME: PropTypes.any, // Type may vary based on ms.input_file?.files_and_pathnames?.mesh_generation?.INPUTTIME
            ARCINFOFILENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
          }),
          resampling_grids: PropTypes.shape({
            SOILTABLENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
            SOILMAPNAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
            LANDTABLENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
            LANDMAPNAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
            GWATERFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
            DEMFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
            RAINFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
            RAINEXTENSION: PropTypes.string,
            DEPTHTOBEDROCK: PropTypes.number,
            BEDROCKFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
            LUGRID: PropTypes.shape(INPUT_FILE_PROPTYPES),
            SCGRID: PropTypes.shape(INPUT_FILE_PROPTYPES),
          }),
          meteorological_data: PropTypes.shape({
            HYDROMETSTATIONS: PropTypes.shape(INPUT_FILE_PROPTYPES),
            HYDROMETGRID: PropTypes.shape(INPUT_FILE_PROPTYPES),
            HYDROMETCONVERT: PropTypes.shape(INPUT_FILE_PROPTYPES),
            GAUGESTATIONS: PropTypes.shape(INPUT_FILE_PROPTYPES),
            GAUGECONVERT: PropTypes.shape(INPUT_FILE_PROPTYPES),
            GAUGEBASENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
          }),
          output_data: PropTypes.shape({
            OUTFILENAME: PropTypes.shape({
              file_database_paths: PropTypes.array,
              path: PropTypes.string,
            }),
            OUTHYDROFILENAME: PropTypes.shape({
              file_database_paths: PropTypes.array,
              path: PropTypes.string,
            }),
            OUTHYDROEXTENSION: PropTypes.string, // This should be a certain file ext
            RIBSHYDOUTPUT: PropTypes.number,
            NODEOUTPUTLIST: PropTypes.shape(INPUT_FILE_PROPTYPES),
            HYDRONODELIST: PropTypes.shape(INPUT_FILE_PROPTYPES),
            OUTLETNODELIST: PropTypes.shape(INPUT_FILE_PROPTYPES),
            OPTSPATIAL: PropTypes.oneOf(Object.values(ProjectConstants.OPTSPATIAL)),
            OPTINTERHYDRO: PropTypes.oneOf(Object.values(ProjectConstants.OPTINTERHYDRO)),
            OPTHEADER: PropTypes.oneOf(Object.values(ProjectConstants.OPTHEADER)),
          }),
          resevoir_data: PropTypes.shape({
            RESPOLYGONID: PropTypes.shape(INPUT_FILE_PROPTYPES),
            RESDATA: PropTypes.shape(INPUT_FILE_PROPTYPES),
          }),
        }),
        modes: PropTypes.shape({
          rainfall_forecasting: PropTypes.shape({
            FORECASTMODE: PropTypes.oneOf(Object.values(ProjectConstants.FORECASTMODE)),
            FORECASTTIME: PropTypes.string,
            FORECASTLEADTIME: PropTypes.string,
            FORECASTLENGTH: PropTypes.string,
            FORECASTFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
            CLIMATOLOGY: PropTypes.string,
            RAINDISTRIBUTION: PropTypes.oneOf(Object.values(ProjectConstants.RAINDISTRIBUTION)),
          }),
          stochastic_climate_forcing: PropTypes.shape({
            STOCHASTICMODE: PropTypes.oneOf(Object.values(ProjectConstants.STOCHASTICMODE)),
            PMEAN: PropTypes.number,
            STDUR: PropTypes.number,
            ISTDUR: PropTypes.number,
            SEED: PropTypes.number,
            PERIOD: PropTypes.number,
            MAXPMEAN: PropTypes.number,
            MAXSTDURMN: PropTypes.number,
            MAXISTDURMN: PropTypes.number,
            WEATHERTABLENAME: PropTypes.shape(INPUT_FILE_PROPTYPES),
          }),
          restart: PropTypes.shape({
            RESTARTMODE: PropTypes.oneOf(Object.values(ProjectConstants.RESTARTMODE)),
            RESTARTINTRVL: PropTypes.number,
            RESTARTDIR: PropTypes.shape(INPUT_FILE_PROPTYPES),
            RESTARTFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
          }),
          parallel: PropTypes.shape({
            PARALLELMODE: PropTypes.oneOf(Object.values(ProjectConstants.PARALLELMODE)),
            GRAPHOPTION: PropTypes.oneOf(Object.values(ProjectConstants.GRAPHOPTION)),
            GRAPHFILE: PropTypes.shape(INPUT_FILE_PROPTYPES),
          }),
        }),
        visualization: PropTypes.shape({
          OPTVIZ: PropTypes.oneOf(Object.values(ProjectConstants.OPTVIZ)),
          OUTVIZFILENAME: PropTypes.shape(INPUT_FILE_PROPTYPES)
        }),
      }),
      linked_dataset: PropTypes.arrayOf(
        PropTypes.shape({
          id: matchesUUID,
          name: PropTypes.string,
        })
      ),
    })
  ),
})